### PR TITLE
Kafka timestamp and timestamp type meta

### PR DESCRIPTION
**Pull request by xianwill**
This PR fixes handling of the Kafka timestamp well-known meta field and adds support for "timestamp_type" so they can be extracted from the Kafka message and merged into the delta record.

### CODE REVIEW

**Comment by xianwill** [comment]
Temporarily converted back to draft. Timestamps look good in `parquet-tools` but not in databricks notebook.

**Comment by xianwill** [comment]
Hrrrm... microsecond precision works for databricks but not parquet-tools. nanosecond precision works for parquet-tools but not databricks.... Seems related to https://github.com/delta-io/delta/issues/643.

**Comment by houqp** [comment]
what error did you get from parquet-tool with microsecond precision?

**Comment by xianwill** [comment]
> What error did you get from parquet-tool with microsecond precision? Is it because the schema for timestamp in delta-rs is hardcoded at nanosecond resulting in parquet schema having the same precision?

@houqp - I think that is it. It doesn't throw, the timestamps are just near epoch because of the precision. I'm gonna reference my local delta-rs and try changing that.

**Comment by xianwill** [comment]
I'm going to need to make a couple of changes in `delta-rs` before merging marking this ready:

1. `delta-rs`->`arrow` timestamp schema mapping - so we can write microsecond precision
2. mapping stats pulled from JSON into parquet. The JSON serialization uses an ISO8601 style formatting (`2021-07-01T17:25:16.256Z`), but the parquet record is a timestamp:

```
############ Column(timestamp) ############
path: meta.kafka.timestamp
max_definition_level: 3
max_repetition_level: 0
physical_type: INT96
logical_type: None
converted_type (legacy): NONE
```

So timestamp columns will need special handling when converting to parquet.

**Comment by houqp** [comment]
> So timestamp columns will need special handling when converting to parquet.

I think this is unavoidable for any type that's not native to JSON :(

**Comment by xianwill** [comment]
There is a bug in the [arrow-rs json writer](https://github.com/apache/arrow-rs/blob/b38a4b6c29ba8b9be02460183c61de86bd9ba7df/arrow/src/json/reader.rs#L930-L931) causing a few nanoseconds to be lost from timestamps. 

The conversion from i64 to f64, back to i64 via `num::cast::cast` in the lines linked above appears to be the cause. I will open a PR there to avoid the cast for `i64` and `u64`. 

```
        let f64val = Value::Number(serde_json::Number::from(1627668684594000000i64)).as_f64().unwrap();
        let i64val: Option<i64> = num::cast::cast(f64val);
        println!("as f64 {:?}", f64val);
        println!("as i64 {:?}", i64val);
```

Output:

```
as f64 1627668684594000000.0
as i64 Some(1627668684593999872)

```

**Comment by xianwill** [comment]
I'd like to get this reviewed for merge as is. The bugfix back to arrow-rs [has been merged](https://github.com/apache/arrow-rs/pull/652), but we'll need to update refs in delta-rs together with kafka-delta-ingest to pick up the fix.

**Review by houqp — APPROVED** [review]

**Comment by houqp** [comment]
@xianwill you might be able to iterate faster by leveraging https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html without having to wait for arrow-rs update in all upstream dependencies. We can even build release artifacts with cargo overrides as well. I do this with roapi: https://github.com/roapi/roapi/blob/main/Cargo.toml

**Pull request merged**
