### PR TITLE
Add test data for playing onto Kafka

### PR DESCRIPTION
**Pull request by xianwill**
This PR adds a test data set we can use locally to play onto Kafka.

### CODE REVIEW

**Review by houqp — COMMENTED** [review]
what's the source of this data? how large is it?

**Comment by xianwill** [comment]
> what's the source of this data? how large is it?

Described in https://github.com/delta-io/kafka-delta-ingest/pull/5/files#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124R49. Didn't realize I staged this after my initial commit 😬.

**Comment by houqp** [comment]
Got it, if this is provided by youtube officially, would be good to site the source link somewhere to give the credit.

**Comment by xianwill** [comment]
> Got it, if this is provided by youtube officially, would be good to site the source link somewhere to give the credit.

Nothing from youtube. The top 100 URL list I sampled is extracted from a wikipedia page. Everything else is just random choice generation. 

I added a line to the README mentioning the specific Wikipedia page:

> URLs sampled for the test data are sourced from Wikipedia's list of most popular websites - https://en.wikipedia.org/wiki/List_of_most_popular_websites.

**Comment by houqp** [comment]
oh, ok, we generated those test data?

**Review by houqp — APPROVED** [review]

**Comment by xianwill** [comment]
> oh, ok, we generated those test data?

yap

**Pull request merged**
