### PR TITLE
Enable Writes to Azure 2

### PR DESCRIPTION
**Pull request by mightyshazam**
This PR is an extension of #114 by @thovoll . It fixes the broken tests, adds support for ARM and adds a test for Azure Blob Storage using Azurite.

### CODE REVIEW

**Comment by rtyler** [comment]
Thanks for the work! Give me some time to review it and compare with the work I had been doing in a branch as well :hugs:

**Comment by rtyler** [comment]
The `cargo clippy` errors are worth addressing, there are some around futures not being resolved which is definitely a bad runtime behavior. Running the build and tests locally is looking generally good. @mightyshazam do you mind if I pull this into a topic branch on this repository, and then we can collaborate on cleaning it up for merge and release?

**Comment by mightyshazam** [comment]
> The `cargo clippy` errors are worth addressing, there are some around futures not being resolved which is definitely a bad runtime behavior. Running the build and tests locally is looking generally good. @mightyshazam do you mind if I pull this into a topic branch on this repository, and then we can collaborate on cleaning it up for merge and release?
> 

Sounds good to me.

**Comment by rtyler** [comment]
@mightyshazam I have pushed the `azure-writes` branch and sent you an invite to act as a collaborator on this repo for that branch. I will close this pull request in favor of the draft: https://github.com/delta-io/kafka-delta-ingest/pull/136

**Pull request closed without merging**
